export const HOME='Home';
export const LOGIN='Login';
export const SIGNUPSELECTION='SignUpSelection';
export const SIGNIN='SignIn';
export const SIGNUP='SignUp';
export const SIGNUPSUPPLIER ='SignUpSupplier';
export const TRUCKLOGO='TruckLogo'
export const TRUCKINFO='TruckInfo';
export const BUSINESSHOUR = 'BusinessHour';
export const SERVINGCUSINE = 'ServingCusine';
export const MENUSETTING ='MenuSetting';
export const COVERPHOTO  ='CoverPhoto';
export const SOCIALMEDIADETAILS ='SocialMediaDetails';
export const SEARCHTRUCK = 'SearchTruck';
export const FINDFOODTRUCK = 'FindFoodTruck';
export const SERVINGCUSINETYPE='ServingCusineType';
export const PROFILE = 'Profile';