export const HOME='Home';
export const LOGIN='Login';
export const SIGNUPSELECTION='SignUpSelection';
export const SIGNIN='SignIn';
export const SIGNUP='SignUp';
export const SIGNUPSUPPLIER ='SignUpSupplier';
export const TRUCKLOGO='TruckLogo'
export const TRUCKINFO='TruckInfo';
export const BUSINESSHOUR = 'BusinessHour';